spring:
  application:
    name: lng-edu-vocabulary

  datasource:
    url: jdbc:postgresql://localhost:5432/vocabulary
    username: vocabulary
    password: vocabulary

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8180

logging:
  level:
    org.mpashka.vocabulary: INFO
