[versions]
java = "25"
springBoot = "4.1.0"
springDepMgmt = "1.1.7"
sqliteJdbc = "3.51.0.0"
postgresql = "42.7.9"
assertj = "3.27.7"
junit = "6.1.0"

[libraries]
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqliteJdbc" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "springBoot" }
spring-dep-mgmt = { id = "io.spring.dependency-management", version.ref = "springDepMgmt" }
